---
- name: restart rsyslog
  become: true
  service:
    name: rsyslog
    state: restarted
  when: haproxy_syslog_enable
  # ignore_errors: yes

- name: restart haproxy
  become: true
  service:
    name: haproxy
    state: restarted
  ignore_errors: yes