---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: haproxy-rockylinux9
    # image: kasmweb/core-rockylinux-9:1.18.0-rolling-daily
    # image: eniocarboni/docker-rockylinux-systemd:9
    # image: rsyslog/rsyslog
    image: rockylinux/rockylinux:9.6-ubi
    image_version: latest
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
    groups:
      - extra_options
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
